### ISSUE TITLE
Can't create more than one Bluepic Projects using IBM Cloud Tools for Swift

### ISSUE THREAD

**Issue by csantanapr** [IBM-Swift/BluePic#275]
Errors just trying to create another project.
Reason I want to create another project I want to have to projects one to be use with XCode 7.3.1 to deploy to production, and another with XCode 8 for initial investigation.

The Tool shuold query first the services I have under my org and space, if the service already exists with the name, then present to the user that a service already exists with the name, and provide to options:
1. Bound new project to the existing service (multiple runtimes can bound to a single weather service and re-use the credentials)
2. Provide a new name for the service to be created and bound present input box with the name a conflict and user can append something like "-2"

Steps to reproduce:
Create App 1
1. Click create
2. Set project to **foo-bluepic**
3. Set Cloud Runtime to **foo-bluepic** 
4. Wait until Cloud Runtime is running (green)

Create App 2
1. Click create
2. Set project to **foo-bluepic-2**
3. Set Cloud Runtime to **foo-bluepic-2** 
4. After a minute you get an Error "The service instance name is taken: Insights for WeatherBluePic-Insights-for-Weather"

Create App 3
1. Click create
2. Set project to **foo-bluepic-3**
3. Set Cloud Runtime to **foo-bluepic-3** 
4. After a minute you get an Error "The service instance name is taken: BluePic-IBM-Push"

![image](https://cloud.githubusercontent.com/assets/1094878/16170805/1d9f48b0-352d-11e6-93f2-e2bfd1dfd390.png)

**Comment by rolivieri** [comment]
@csantanapr Hello, since you are using The IBM Cloud Tools for project generation, I’d recommend using their feedback(http://ibm.biz/Bd4QPP) page to provide feedback and/or report any issues you may be running into. I will also share these issues with the tech lead for the IBM Cloud Tools for Swift.

**Comment by ecompton3** [comment]
Hwy @csantanapr,

I'm a developer on the ICT tool. Currently it is not possible to have multiple BluePic apps because of current Cloud Foundry and Bluemix restrictions. The app itself looks for services with a specific name and Cloud Foundry does not permit having duplicate names. Also, the Object-Storage and Alchemy services are currently limited to one free plan per Org. We're looking to improve this experience but as of right now this is a limitation of the platform itself

**Comment by csantanapr** [comment]
Ah thanks ! I didn't know about the limit of one.

**Comment by rolivieri** [comment]
@csantanapr Just a few more details. The “declared services” extension at the top of the manifest.yml (https://console.ng.bluemix.net/docs/develop/deploy_button.html, https://developer.ibm.com/devops-services/2015/02/18/share-code-new-deploy-bluemix-button/) specifies the syntax (service name, service label, etc.) that should be followed for the services that are expected to be set up before the app is deployed. The `deploy to bluemix` button functionality and the ICT tool leverage this when provisioning an app. We are closing this issue as a known limitation (and it also pertains more to the user experience for the ICT Tool app than BluePic). Any other questions related to BluePic, just let us know, thx.

**Comment by csantanapr** [comment]
no
