### ISSUE TITLE
Cloud Runtime doesn't show correct runtime status and Client App missing

### ISSUE THREAD

**Issue by csantanapr** [IBM-Swift/BluePic#276]
Using IBM Cloud Tools for Swift to create BluePic project, the Client App shows up empty and Runtime doesn't show proper status

Steps to reproduce:
1. Click new BluePic project
2. Enter project name "foo-bluepic"
3. Enter Cloud Runtime name "foo-bluepic"
4. Click Create
5. Wait and Monitor the Logs in Bluemix until app is running (i.e. Logs) 

Results:
Next screen doesn't show the Client App only a label 1 Client App
Multiple macOS notifications about Runtime stopped, Runtime started, Runtime running
Screen still shows status Not Running
![image](https://cloud.githubusercontent.com/assets/1094878/16170981/24eb0866-3532-11e6-93e9-f1d415877c3e.png)

To work around Go back one screen and then drill back in and you see the Client App and  then it dhows the Client App and correct status
![image](https://cloud.githubusercontent.com/assets/1094878/16170986/4bc606c0-3532-11e6-892a-ce9c11ffa964.png)

**Comment by rolivieri** [comment]
@csantanapr Hello, since you are using The IBM Cloud Tools for project generation, I’d recommend using their feedback(http://ibm.biz/Bd4QPP) page to provide feedback and/or report any issues you may be running into. I will also share these issues with the tech lead for the IBM Cloud Tools for Swift.

**Comment by ecompton3** [comment]
@csantanapr This is a known issue and will be fixed in a future release. We'll be adding a changelog to our site to better communicate these things shortly. In the meantime please use the link Ricardo provided or our DW Answers tag https://developer.ibm.com/answers/topics/cloud-tools-for-swift/ for a direct response from our team

**Comment by csantanapr** [comment]
When I created this issue I also submitted corresponding entries using the form with the link to the issues in github. 
It's more convenience to report using github 🙀

Looking forward to more awesomeness 👍🏼

**Comment by rolivieri** [comment]
@csantanapr We are closing this issue since it pertains to the IBM Cloud Tools team (not the BluePic team). Any other questions related to BluePic, just let us know, thanks!

**Comment by csantanapr** [comment]
np
