### ISSUE TITLE
Validate change to pod file (removing BMSSecurity entry).

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/BluePic#294]

**Comment by tfrank64** [comment]
Current Behavior:
Before changing podfile, image uploads on second start of the app doesn't work. I logged out and tried again a couple times and it eventually started working without fail.

**Comment by tfrank64** [comment]
I then updated the Podfile so BMSSecurity 1.1.4 is implicitly pulled down. I delete the app, re-install and everything is still working fine.

**Comment by tfrank64** [comment]
From my debugging, the problem seems to be with the expiration timestamp generated by the iOS MCA client and sent up to the BluePic server. I will confirm in a bit, when the current expiration time should expire, this failure happens here: https://github.com/ibm-bluemix-mobile-services/bms-mca-serversdk-swift/blob/master/Sources/MobileClientAccess/Core/MobileClientAccessSDK.swift#L69

**Comment by tfrank64** [comment]
Sent email to MCA team for possible solution.

**Comment by tfrank64** [comment]
Had a call with Oded, he will test the issue on a physical device tomorrow. I couldn't reproduce the error on the simulator, but it still happens on my iPhone.

**Comment by tfrank64** [comment]
Determined a fix by debugging with Oded. We can use the fix after they release tomorrow hopefully.
