### ISSUE TITLE
BluePic does not work on Bluemix

### ISSUE THREAD

**Issue by tpeg5stan** [IBM-Swift/BluePic#386]
I clicked the button deploy into Bluemix, then it deployed properly. I then edited on jazz hub the cloud_config.json with the credentials associated to my services. 
Note that I use a PC under windows, and not macOS.
My app seems to work correctly, as the front page is displayed, but the buttons are not clickable. 

You can see the result here : https://bluepic-kapi-932.eu-gb.mybluemix.net/#/
Any idea how I could investigate this ?

**Comment by tfrank64** [comment]
@tpeg5stan Well it looks like you are getting 404 errors for images so it may be that there are just no images. That may be why the buttons don't seem to do anything, otherwise I think the "I'll sign in later" button should work and take you to all the photos.

Have you populated your database and object storage with image data? Details are in this section: https://github.com/IBM-Swift/BluePic#4-populate-cloudant-database and the one right after.

**Comment by tfrank64** [comment]
@tpeg5stan Did you find your database to be populated? Were there any other issues?
I can close this issue soon if I don't hear anything back.

**Comment by tpeg5stan** [comment]
Oh yes, I completely forgot about that, I went to work on other things, you can close this ticket.
