### ISSUE TITLE
Trying to run Methods 1 & 2 don't work

### ISSUE THREAD

**Issue by ljbennett62** [IBM-Swift/BluePic#394]
Using the "Deploy to Bluemix" button issues the same error as running Method 2:

I get the error "can't find cloud_config.json".  I see the file in the following directory:

/BluePic/BluePic-Server/Sources/BluePicApp/

any ideas how to fix it. When I print the variable "path" that is the failing file "Configuration.swift"  - it comes back as nil.  

any ideas?

**Comment by tfrank64** [comment]
@ljbennett62 Which method did you try? The Cloud Tools for Swift method or the manual method?

I assume you see this error on Bluemix?
Also, what branch of BluePic did you use?

**Comment by ljbennett62** [comment]
both methods - 1) The Cloud tools and 2) the manual method.  Yes - am seeing it in Bluemix. I am using the Master branch.

**Comment by ljbennett62** [comment]
so got a bit further when I went in the code (Configuration.swift) and manually set:
let finalPath: String = "/Users/laurabennett/2017-NewRole/Code/BluePic/BluePic-Server/cloud_config.json"

I then get the following error when I do that:

![image](https://cloud.githubusercontent.com/assets/17774650/24618800/0d00c084-184d-11e7-843b-7004f4cee49f.png)

**Comment by tfrank64** [comment]
There might be another issue here, but we at least need to find a fix for not being able to create new MCA Bluemix services (https://github.com/IBM-Swift/BluePic/issues/396). MCA was replaced with App ID, so not having it can prevent successful app deployments.

**Comment by ljbennett62** [comment]
@tfrank64 - HI Taylor - so are you looking into this?

**Comment by tfrank64** [comment]
@ljbennett62 Yes, I am looking into it.

**Comment by ljbennett62** [comment]
ok - tx - let me know if you need me to try something

**Comment by tfrank64** [comment]
@ljbennett62 Would you be willing to try and deploy a new BluePic application? I've updated BluePic to use App ID which was part of the problem, since MCA was deprecated. I got it to work through both IBM Cloud Tools and the Deploy to Bluemix button, let me know if it works for you.

Note, you may still see `Could not find cloud_config.json` but it should still work because it can access environment variables on Bluemix.

**Comment by ljbennett62** [comment]
yes - let me give it a try!  tx

**Comment by ljbennett62** [comment]
@tfrank64 - so the deploy to bluemix button worked!! yay! - now I am going to try to deploy locally. Thanx for the quick turnaround

**Comment by ljbennett62** [comment]
btw - i just noticed you took out Alchemy and are now using Visual Recognition - are you planning to add NLU?

**Comment by tfrank64** [comment]
Your welcome, glad it is working now!

We don't have plans currently to add NLU. The change you mentioned was because Alchemy Vision was deprecated in favor of Watson Visual Recognition.

**Comment by ljbennett62** [comment]
@tfrank64 - so it gets deployed but when I click the URL in BM - the links on the app (using Chrome) don't do anything. "I'll sign in later" and "sign in with facebook"

**Comment by tfrank64** [comment]
@ljbennett62 Well the facebook button is grayed out because it is not enabled right now. The sign in later link should work if you finished going through the Readme after the Deploy to Bluemix button step. You most likely still need to populate the database: https://github.com/IBM-Swift/BluePic#4-populate-cloudant-database

**Comment by ljbennett62** [comment]
ok - let me continue

**Comment by tfrank64** [comment]
I will close this issue tomorrow since deployment itself is working.

**Comment by ljbennett62** [comment]
sounds good - tx for all your help!
