### ISSUE TITLE
populator.sh doesn't match README.md 

### ISSUE THREAD

**Issue by iainhouston** [IBM-Swift/BluePic#403]
The script:

```
cloudantFolder=`cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd`/cloudantNoSQLDB
objectStorageFolder=`cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd`/Object-Storage
$cloudantFolder/populator.sh --username=<cloudant username> --password=<cloudant password> --projectId=<object storage projectId>
$objectStorageFolder/populator.sh --userId=<object storage username> --password=<object storage password> --projectId=<object storage projectId> --region=<object storage region>
```

according to the README is supposed to be invoked thus: 
```
./populator.sh --username=<cloudant username> --password=<cloudant password> --projectId=<object storage projectId>
```

but it looks instead as though the script should be edited with the credentials, then invoked how? What is intended?

As is:
```
./populator.sh: line 21: syntax error near unexpected token `newline'
./populator.sh: line 21: `$cloudantFolder/populator.sh --username=<cloudant username> --password=<cloudant password> --projectId=<object storage projectId>'
```

**Comment by tfrank64** [comment]
@iainhouston Looks like you are referring to the populator.sh script in the `/Cloud-Scripts/` directory. We don't provide instructions on using that one because it is a convenience script for development, it requires you to edit the script instead of just providing command line arguments.

Anyway, the populator scripts we ask the user to use are in the `Cloud-Scripts/cloudantNoSQLDB/` and `Cloud-Scripts/Object-Storage/` directories.

**Comment by iainhouston** [comment]
Oops! Please excuse my speed-reading!
